[package]
name = "luminance-gl"
version = "0.1.0"
authors = ["Dimitri 'phaazon' Sabadie <dimitri.sabadie@gmail.com>"]

[dependencies]
gl = "0.5.2"
luminance = { git = "https://github.com/phaazon/luminance-rs.git" }
